### ISSUE TITLE
Repo has no license

### ISSUE THREAD

**Issue by williamblevins** [shapedbyrainstudios/ink-dialogue-system#6]
> Please feel free to take the system from this example and use it however you'd like!

Even though that statement is in the README.txt. Technically, the rules here apply https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by shapedbyrainstudios** [comment]
Thanks @williamblevins ! Agreed. I have added the MIT license to all branches of the repo.
